how to tranfer file to server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -3,8 +3,24 @@
 
 if [ "$#" -lt 3 ]; then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+	exit 1
+fi
+# assigning parameters to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabling strict host key checking
+
+scp -o "StrictHostChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# checking if the file transfer was successful
+
+if [$? -eq 0]
+then
+	echo "File Transferred Successfully"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+	echo "File Transfer failed"
 fi
